name = "abcd-reverse-proxy"
main = "./worker/worker.js"
compatibility_date = "2024-07-01"

[build]
command = "npm run build"
publish = "public"

[vars]
TARGET_URL = "https://luogu.com"   # 替换为实际目标网站
SITE_URL = "https://luogu.qpoem.org.cn"               # 替换为代理站点域名
