name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install Pages CLI
        run: npm install -g wrangler
        
      - name: Deploy
        run: wrangler pages deploy public --project-name=abcd-proxy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}